spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

app:
  timezone: Europe/Minsk

telegram:
  bot:
    username: ${TELEGRAM_BOT_USERNAME:}
    token: ${TELEGRAM_BOT_TOKEN:}